name: CI hubla-import-transactions-client

on:
  push:
    paths:
      - 'client/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7 )
          echo "::set-output name=sha::$SHA"

      - name: Build docker image
        run: docker build -t danielrodriguess/hubla-import-transactions-client:${{ steps.generate_sha.outputs.sha }} client

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push danielrodriguess/hubla-import-transactions-client:${{ steps.generate_sha.outputs.sha }}
          docker tag danielrodriguess/hubla-import-transactions-client:${{ steps.generate_sha.outputs.sha }} danielrodriguess/hubla-import-transactions-client:latest
          docker push danielrodriguess/hubla-import-transactions-client:latest
